name: Lint

on:
  push:
    branches: [master,dev]
  pull_request:
    branches: [master,dev]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        if: startsWith(github.ref, 'refs/heads/')
        uses: actions/checkout@v2

      - name: Set up Node.js
        if: startsWith(github.ref, 'refs/heads/')
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install dependencies
        if: startsWith(github.ref, 'refs/heads/')
        run: yarn install

      - name: Run linters
        if: startsWith(github.ref, 'refs/heads/')
        run: yarn fix

      - name: push
        if: startsWith(github.ref, 'refs/heads/')
        uses: github-actions-x/commit@v2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'lint'
          force-add: 'false'
          name: Github Action
          email: it@dipperin.io
