name: Lint

on:
  - push
  - pull_request

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn install

      - name: Run linters
        uses: yarn fix
      
      - name: Commit changes
      uses: EndBug/add-and-commit@v2 
      with:
        author_name: Github Action
        author_email: it@dipperin.io
        message: "Auto Lint"
        path: "."
        pattern: "*.*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}